# Generated by Django 3.1.4 on 2021-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_onorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='onorder',
            name='status',
            field=models.CharField(blank=True, default='pending...', max_length=100),
        ),
    ]
