# Generated by Django 3.1.4 on 2021-02-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_onorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='onorder',
            name='contact',
        ),
    ]
