# Generated by Django 3.1.4 on 2021-02-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210226_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
